name: job-matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - selenium=4.18.1
  - beautifulsoup4=4.12.3
  - requests=2.31.0
  - python-dotenv=1.0.1
  - scikit-learn=1.4.1
  - nltk=3.8.1
  - spacy=3.7.4
  - pip:
    - webdriver-manager==4.0.1 